openapi: 3.0.0
servers: []
info:
  version: 0.1.0
  title: Static file yaml
  description: This is a API specification for the static files of the mock server
  contact:
    name: MaaS Alliance
    url: 'https://maas-alliance.eu/'
  license:
    name: Apache 2.0
    url: 'https://github.com/maas-alliance/apis/blob/master/LICENSE'
tags:
  - name: Static
    description: Deliver static files like redoc documentation
    externalDocs:
      description: idea found here
      url: 'https://github.com/zalando/connexion/issues/441'
paths:
  /:
    get:
      operationId: api.static_redoc
      description: HTML file with rendered OpenAPI reference.
      tags:
        - Static
      responses:
        '200':
          description: Successfully loaded html page
          content: 
            text/html:
              schema:
                type: string
